### ISSUE TITLE
Add CompareTheTriplets.py

### ISSUE THREAD

**Issue by PrajjawalBanati** [PrajjawalBanati/Hackerrank_Problems#1]

**Comment by AmirHMaleki** [comment]
Hello, I want to contribute. Just I need to know how you want the output array (c) look like. Also if you provide an example it'd be super!

**Comment by PrajjawalBanati** [comment]
Hello, @AmirHMaleki Here is the problem statement read and understand what they need. If any Queries feel free to contact

https://www.hackerrank.com/challenges/compare-the-triplets/problem

**Comment by PrajjawalBanati** [comment]
![image](https://user-images.githubusercontent.com/32102563/66680936-47c3bf00-ec8f-11e9-917b-1f0bddfe7d8c.png)
The following example may be of some help

**Comment by PrajjawalBanati** [comment]
@AmirHMaleki Please refer to this example
